site_name: IT Base
site_description: "A personal knowledge base for programming and more"
site_author: "NkkMkk"

theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: red
    accent: red
  font:
    text: Roboto
    code: Roboto Mono
  logo: images/logo.png
  favicon: images/favicon.ico
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.tabs.link
    - search.suggest
    - search.highlight

extra_css:
  - assets/overrides.css
extra_javascript:
  - assets/open-links.js

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true

nav:
  - Home: index.md
  - SQL: 
      - Overview: sql/index.md
      - SELECT Clause: sql/select-clause.md
  - Programming:
      - Overview: programming/index.md
      - Python: programming/python.md
      - JavaScript: programming/javascript.md
      - Tips & Snippets: programming/snippets.md

plugins:
  - search
