site_name: IT Base
site_description: "A personal knowledge base for programming and more"
site_author: "NkkMkk"

theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  logo: images/logo.svg
  favicon: images/logo.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.footer

    - content.code.copy
    - content.tabs.link

    - search.suggest
    - search.highlight

extra_css:
  - assets/overrides.css
extra_javascript:
  - assets/open-links.js

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true

nav:
  - Home: index.md
  - SQL: 
      - Introduction to SQL: sql/index.md
      - SELECT Clause: sql/select-clause.md
      - WHERE Clause: sql/where-clause.md

plugins:
  - search
