site_name: IT Base
site_description: "A personal knowledge base for programming and more"
site_url: ""

theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: red
    accent: red
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.tabs.link
    - search.suggest
    - search.highlight

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Programming:
      - Overview: programming/index.md
      - Python: programming/python.md
      - JavaScript: programming/javascript.md
      - Tips & Snippets: programming/snippets.md
  - DevOps:
      - Overview: devops/index.md
      - Docker: devops/docker.md
      - Git: devops/git.md
  - Data:
      - Overview: data/index.md
      - SQL: data/sql.md
      - Pandas: data/pandas.md
  - More:
      - Notes: more/notes.md
      - Resources: more/resources.md

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/